version: '3'
services:
  dynamo:
    restart: always
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - db_data:/home/dynamodblocal
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
  api:
    image: my_node:latest
    restart: always
volumes:
    db_data: {}